Fix alignment of test structs
Clang complains for subscript.cpp:
error: requested alignment is less than minimum alignment of 8 for type 'S<float>'

The reason is that the struct also contains a double that requires
alignment of at least 8 bytes on x86_64 and the programm is thus
ill-formed. Remedy by taking alignof(double) into account.

Other approaches explored:
1) Adding multiple alignas, the compiler should use the "strictest
(largest) non-zero expression". However GCC (including the latest
version 10.2.0) always applies the last attribute and older versions
of Clang (tested: 5.0.2 as in Xcode 9.4.1) also error out.
2) Using std::max to get the maximum. GCC complains that the result
is not an integer constant.